language: python
python:
    - "3.6"
    - "3.7"
services: 
    - mysql
install: 
    - pip install -r requirements.txt
before_script: 
    - mysql -e 'create database test;' -u root
    - python manage.py collectstatic
script: 
    - python manage.py test