language: python
    python:
      - "3.5"
      - "3.6"
    services: 
      - mysql
    env:
      - DJANGO_VERSION=2.0.0
      - DJANGO_VERSION=2.1.0      
      - DJANGO_VERSION=2.2.3
    install: 
      - 
      - pip install -r requirements.txt
    before_script: 
      - mysql -e 'create database test;' -u root
    script: 
      - python manage.py test