# Generated by Django 3.0.2 on 2020-02-11 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gebietseinheit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionalschluessel', models.CharField(help_text='12-stelliger amtlicher Regionalschlüssel', max_length=12)),
                ('satzart', models.CharField(choices=[('10', 'Bundesland'), ('20', 'Regierungsbezirk'), ('30', 'Region'), ('40', 'Kreis'), ('50', 'Gemeindeverband'), ('60', 'Gemeinde')], help_text='Politische Ebene', max_length=2)),
                ('textkennzeichen', models.CharField(blank=True, choices=[('41', 'Kreisfreie Stadt'), ('42', 'Stadtkreis (nur in Baden-Württemberg)'), ('43', 'Kreis'), ('44', 'Landkreis'), ('45', 'Regionalverband (nur im Saarland)'), ('50', 'Verbandsfreie Gemeinde'), ('51', 'Amt'), ('52', 'Samtgemeinde'), ('53', 'Verbandsgemeinde'), ('54', 'Verwaltungsgemeinschaft '), ('55', 'Kirchspielslandgemeinde'), ('56', 'Verwaltungsverband'), ('58', 'Erfüllende Gemeinde'), ('60', 'Markt'), ('61', 'Kreisfreie Stadt'), ('62', 'Stadtkreis (nur in Baden-Württemberg)'), ('63', 'Stadt'), ('64', 'Kreisangehörige Gemeinde'), ('65', 'gemeindefreies Gebiet-bewohnt'), ('66', 'gemeindefreies Gebiet-unbewohnt'), ('67', 'Große Kreisstadt')], help_text='Bezeichnung der kommunalen Einheit', max_length=2)),
                ('land', models.CharField(help_text='Bundesland-Schlüssel', max_length=2)),
                ('regierungsbezirk', models.CharField(blank=True, help_text='Regierungsbezirks-Schlüssel', max_length=1)),
                ('kreis', models.CharField(blank=True, help_text='Kreis-Schlüssel', max_length=2)),
                ('gemeindeverband', models.CharField(blank=True, help_text='Gemeindeverband-Schlüssel', max_length=4)),
                ('gemeinde', models.CharField(blank=True, help_text='Gemeinde-Schlüssel', max_length=3)),
                ('name', models.CharField(help_text='Name der Gebietseinheit', max_length=50)),
                ('flaeche', models.DecimalField(decimal_places=2, help_text='Fläche in km2', max_digits=5, null=True, verbose_name='Flaeche in km2')),
                ('bevoelkerung', models.IntegerField(help_text='Einwohnerzahl', null=True)),
                ('bevolkerungsdichte', models.IntegerField(help_text='Einwohner pro km2', null=True)),
                ('postleitzahl', models.CharField(blank=True, help_text='Postleitzahl des Verwaltungssitzes', max_length=5)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Längengrad WGS84', max_digits=9, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Breitengrad WGS84', max_digits=9, null=True)),
                ('verstaedterung', models.CharField(blank=True, choices=[('1', 'Stadt'), ('2', 'Kleinere Stadt oder Vorort'), ('3', 'ländliches Gebiet')], help_text='Grad der Verstädterung (nach Eurostat DEGURBA)', max_length=1)),
                ('stand', models.DateField(help_text='Zeitpunkt des Standes des Eintrages')),
                ('erstellt_am', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Gebietseinheiten',
                'unique_together': {('regionalschluessel', 'stand')},
            },
        ),
        migrations.CreateModel(
            name='Gebietseinheit_Erweiterung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ortsname_suche', models.CharField(help_text='Gemeindename, so wie er im Webscraping gesucht werden soll', max_length=100, verbose_name='Gemeindename für Suche')),
                ('ansprechpartner_anrede', models.CharField(blank=True, choices=[('1', 'Herr'), ('2', 'Frau')], max_length=1)),
                ('ansprechpartner_vorname', models.CharField(blank=True, max_length=100)),
                ('ansprechpartner_name', models.CharField(blank=True, max_length=100)),
                ('ansprechpartner_funktion', models.CharField(blank=True, help_text='Bürgermeister, Hauptamstleiter, Stabstelle BB etc.', max_length=100, verbose_name='Funktion Ansprechpartner')),
                ('ansprechpartner_telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon Ansprechpartner')),
                ('ansprechpartner_mail', models.EmailField(blank=True, help_text='Persönliche oder Funktions E-Mailadresse', max_length=100, verbose_name='E-Mail Ansprechpartner')),
                ('strasse_gv', models.CharField(help_text='Anschrift der Gemeindeverwaltung', max_length=100, verbose_name='Straße und Hausnummer GV')),
                ('plz_ort_gv', models.CharField(help_text='Anschrift der Gemeindeverwaltung', max_length=100, verbose_name='PLZ und Ort GV')),
                ('homepage_gv', models.CharField(blank=True, help_text='Offizielle Homepage der Gemeinde', max_length=100, verbose_name='Homepage GV')),
                ('mail_gv', models.EmailField(blank=True, help_text='allg. E-Mail der Gemeindeverwaltung', max_length=254, verbose_name='E-Mail GV')),
                ('wappen', models.FileField(blank=True, help_text='Wappen der Kommune als .png in Auflösung 140px x 142px', upload_to='wappen/')),
                ('erstellt_am', models.DateField(auto_now_add=True)),
                ('gebietseinheit', models.ForeignKey(help_text='Name der Kommune', limit_choices_to={'land': '08', 'satzart': '60'}, on_delete=django.db.models.deletion.PROTECT, to='basisdaten.Gebietseinheit')),
            ],
            options={
                'verbose_name_plural': 'Gebietseinheiten Erweiterung',
            },
        ),
        migrations.CreateModel(
            name='Bearbeitungsstand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearbeitungsstand', models.CharField(choices=[('0', 'unbearbeitet'), ('1', 'Rohtreffer generiert'), ('2', 'Rohtreffer bereinigt'), ('3', 'Kodierauftrag zugeteilt'), ('4', 'Rohtreffer kodiert'), ('5', 'Treffer aufbereitet'), ('6', 'Ergebnisse veröffentlicht'), ('7', 'Ergebnisse in ext. Prüfung'), ('8', 'Ergebnisse geprüft')], default='0', help_text='Bearbeitungsstand der Kommune', max_length=1)),
                ('erstellt_am', models.DateField(auto_now_add=True)),
                ('gebietseinheit', models.ForeignKey(help_text='Name der Kommune', limit_choices_to={'land': '08', 'satzart': '60'}, on_delete=django.db.models.deletion.PROTECT, to='basisdaten.Gebietseinheit')),
            ],
            options={
                'verbose_name_plural': 'Bearbeitungsstand',
                'get_latest_by': 'erstellt_am',
                'unique_together': {('gebietseinheit', 'bearbeitungsstand')},
            },
        ),
    ]
