# Generated by Django 3.0.3 on 2020-02-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddb_showcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suchanfrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('querystring', models.CharField(blank=True, help_text='Suchanfrage', max_length=100, null=True)),
                ('results', models.IntegerField(blank=True, help_text='Anzahl der angezeigten Treffer', null=True)),
                ('date_of_query', models.DateField(auto_now_add=True, help_text='Datum der Suchanftrage wird automatisch eingefügt')),
            ],
            options={
                'verbose_name_plural': 'Suchanfragen',
            },
        ),
    ]
